config = {
    'scheduler': 'slurm',
    'mpiexec': 'srun',
    'serial_python': 'singularity exec /users/mpeterse/base.sif python3',
    'nodes': [
            ('debug', {'queue': 'slurm',
                        'cores': 128,
                        'memory': '200G',
                        'extra_args': ['--account=project_465001017']}),
            ('small', {'queue': 'slurm',
                        'cores': 128,
                        'memory': '512G',
                        'extra_args': ['--account=project_465001017']}),
            ('standard', {'queue': 'slurm',
                        'cores': 128,
                        'memory': '512G',
                          'extra_args': ['--account=project_465001017']}),
            ('standard-g', {'queue': 'slurm',
                        'cores': 128,
                        'memory': '512G',
                          'extra_args': ['--account=project_465001017']}),
            ('small-g', {'queue': 'slurm',
                        'cores': 128,
                        'memory': '512G',
                          'extra_args': ['--account=project_465001017']}),
            ('largemem', {'queue': 'slurm',
                        'cores': 128,
                        'memory': '512G',
                          'extra_args': ['--account=project_465001017']}),
    ],
    'maximum_total_task_weight': 4
}
