config = {
    'scheduler': 'slurm',
    'mpiexec': '',
    'nodes': [
            ('xeon24', {'queue': 'slurm',
                        'cores': 24,
                        'memory': '256G'}),
            ('xeon24_512', {'queue': 'slurm',
                            'cores': 24,
                            'memory': '512G',}),
            ('xeon24_week', {'queue': 'slurm',
                            'cores': 24,
                            'memory': '256G',}),
            ('xeon24_test', {'queue': 'slurm',
                            'cores': 24,
                            'memory': '500G',}),
            ('xeon32_week', {'queue': 'slurm',
                            'cores': 32,
                            'memory': '4096G',}),
            ('xeon32_4096', {'queue': 'slurm',
                            'cores': 32,
                            'memory': '4096G',}),
             ('xeon40', {'queue': 'slurm',
                        'cores': 40,
                        'memory': '384G'}),
            ('xeon40_768', {'queue': 'slurm',
                            'cores': 40,
                            'memory': '750G'}),
            ('xeon40_clx', {'queue': 'slurm',
                            'cores': 40,
                            'memory': '384'}),
            ('xeon56', {'queue': 'slurm',
                        'cores': 56,
                        'memory': '512G'}),
            ('epyc96',  {'queue': 'slurm',
                        'cores': 96,
                        'memory': '768G'}),
            ('a100_week', {'queue': 'slurm',
                        'cores': 128,
                        'memory': '512G'}),
            ('a100', {'queue': 'slurm',
                        'cores': 128,
                        'memory': '512G'}),
            ('sm3090el8', {'queue': 'slurm',
                        'cores': 8,
                        'memory': '191G',
                        'extra_args': ['--gres=gpu:RTX3090:1','--export=ALL,MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,OPENBLAS_NUM_THREADS=1']}),
            ('sm3090_devel', {'queue': 'slurm',
                        'cores': 8,
                        'memory': '191G',
                        'extra_args': ['--gres=gpu:RTX3090:1','--export=ALL,MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,OPENBLAS_NUM_THREADS=1']}),            
            ('sm3090', {'queue': 'slurm',
                        'cores': 8,
                        'memory': '191G',
                        'extra_args': ['--gres=gpu:RTX3090:1','--export=ALL,MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,OPENBLAS_NUM_THREADS=1']}),
            ('sm3090_768', {'queue': 'slurm',
                            'cores': 8,
                            'memory': '768G',
                            'extra_args': ['--gres=gpu:RTX3090:1','--export=ALL,MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,OPENBLAS_NUM_THREADS=1']})
    ],
    'maximum_diskspace': 4
}
